### ISSUE TITLE
Style issues: progress bar & play button

### ISSUE THREAD

**Issue by Kozou4ever** [Comfy-Themes/Spicetify#102]
## Steps to reproduce: 
Load the Comfy theme, then play any music as you wish

## Expected behavior:

- A proper display of the play button
- The display of the song's progress bar

## Actual behavior 
As you can see on the screenshot herewith, there is a slight issue as regards the play button and the progress bar:
- The playing button seems to be covered by another image
- The progress bar seems to be concealed

## Screenshot

<details>
<summary> Click here to unfold </summary>

![image](https://user-images.githubusercontent.com/72155852/199064478-be30c068-a604-4d52-85d7-b2cae3f993bc.png)

</details>

**Comment by ohitstom** [comment]
This is not a comfy issue, remove other themes extensions from your config. I will not be furthering this thread or responding as this is 100% not a comfy issue.

**Comment by kyrie25** [comment]
This is a conflict with the Bloom extension to be exact, hopefully that would give you some clue.

**Comment by Kozou4ever** [comment]
Yep indeed, there was a conflict between the Bloom extension and the Comfy theme. But in spite of that, the progress bar is still missing even though I only have the Comfy theme and extension installed.
![image](https://user-images.githubusercontent.com/72155852/199270749-4da413ba-2206-4ae8-b0e7-c99fdd285e12.png)

**Comment by Kozou4ever** [comment]
Well I don't know why it didn't work previously... I want to apologize for the loss of time... I just deleted the theme and the extension and installed them back, just like that the progress bar reappaeared... Sorry 🙏
