### ISSUE TITLE
Weird rounding behaviour when scroll down playlists

### ISSUE THREAD

**Issue by theRealPadster** [Comfy-Themes/Spicetify#103]
I noticed when you scroll down your playlists, it looks funny since the rounded corners from the top section stay and are put against the non-rounded corners of the bottom section. 

Potential fix: 
- See if it's possible to keep a thin bar in between the two sections when you scroll (maybe using `position: sticky`)
- This would look best if the rounded corners were kept. You could maybe add a border-radius on the playlist parent container. 

When scrolled at the top:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1565883/206031566-b759f433-3e64-4e48-ba08-5138125d2b80.png">
When scrolled down:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1565883/206031714-c147ca6a-aa5d-4547-88ce-69f142b330d2.png">

**Comment by ohitstom** [comment]
This is not an issue with our theme. It is an issue with the cover art extension. Feel free to make a PR.

**Comment by ohitstom** [comment]
Nevermind i see what you mean, i dont really dev this anymore but @kyrie25 might be able to get around to it, seems very easy.

**Comment by ohitstom** [comment]
Changing lines 20 in _navbar.scss
```
margin: 24px 12px 0 12px;
>
margin: 24px 12px 12px 12px;
```

Is a quick and dirty fix, though it moves everything down.

![image](https://user-images.githubusercontent.com/22730962/209426321-a25a77c5-2dde-4128-bea4-51708f1ccb5f.png)
![image](https://user-images.githubusercontent.com/22730962/209426322-2088631c-7d7a-4225-973f-449b7f30f6b9.png)

**Comment by ohitstom** [comment]
solved via e920f635c96572413583b8df078d944ae7f23002

**Comment by theRealPadster** [comment]
Haha yeah I guess that works, thanks
