### ISSUE TITLE
Revert home icon

### ISSUE THREAD

**Issue by vathanac** [Comfy-Themes/Spicetify#107]
Currently
![image](https://user-images.githubusercontent.com/87689818/210216845-beba95bf-ccb8-44e9-b747-2b6ad224b0e5.png)

Custom Icon
![image](https://user-images.githubusercontent.com/87689818/210216851-44d492bb-b50c-4dca-9a81-9ad24fe7351f.png)

**Comment by vathanac** [comment]
![image](https://user-images.githubusercontent.com/87689818/210216927-62580d97-474a-4fec-a6bc-c27041374829.png)

**Comment by ohitstom** [comment]
Spotify update that's not technically supported, I'll work on fixing this at some point

**Comment by ohitstom** [comment]
#116
