### ISSUE TITLE
Colour scheme randomly switches

### ISSUE THREAD

**Issue by Jazza-231** [Comfy-Themes/Spicetify#108]
I absolutely love this theme, overall it's just great! But there is one issue that is getting quite annoying, and that is the seemingly random colour switches.  I use the default colour comfy, but randomly when switching to the program, closing the marketplace, and other random things it switches to a different colour scheme, most commonly the sunset and mono theme. While typing this I went back to Spotify to check what the colours were called and it switched again by itself, this time to sakura.
It's not a massive problem but is quite annoying as it happens so often, the only way to fix it is to go to the marketplace and press on the comfy colour again (the drop-down still thinks it is on the comfy colour scheme). If there is some fix then that would be great! 
Correct colour, comfy
![image](https://user-images.githubusercontent.com/81956724/212850923-4692cc88-7d55-4d03-b843-49b27e4be666.png)
Thinking it is on comfy, but it is actually on a different colour scheme
![image](https://user-images.githubusercontent.com/81956724/212851370-947dc0cd-6082-4cd3-8dd3-d44f21f6892d.png)
Hope this all makes sense! (Please tell me if you need more info, maybe a video or something?)

**Comment by ohitstom** [comment]
you sure this isn't an option you have enabled in marketplace by accident? there are a few settings that give randomize/song specific coloring

I don't see the theme being able to do this on its own

**Comment by kyrie25** [comment]
Disable color switching feature on Marketplace settings
Not a theme issue.

**Comment by Jazza-231** [comment]
Oh goodness me I didn't even see that...Well yes, it's certainly not an issue with your theme then, so sorry about the trouble but thanks for the help anyways :D
