### ISSUE TITLE
Song name cutoff in search menu

### ISSUE THREAD

**Issue by Lncr00** [Comfy-Themes/Spicetify#110]
![image](https://user-images.githubusercontent.com/113306716/213913741-b377ee7e-6b60-45c1-97ee-ff8d0de981c9.png)
-Dimensions of the tab is roughly 1080x650; it's on a vertical monitor.
-Issue happens across all colour themes, not just Mono.
-Only happens in the 'All' tab of the search results.

**Comment by ohitstom** [comment]
#116
