### ISSUE TITLE
timestamp for songs hidden

### ISSUE THREAD

**Issue by thaynos** [Comfy-Themes/Spicetify#112]
![image](https://user-images.githubusercontent.com/83282129/215262739-dfa0178e-56cb-45d3-ae3c-6c24a7ae4e02.png)

**Comment by kyrie25** [comment]
Feature, not a bug

https://github.com/Comfy-Themes/Spicetify/blob/main/Comfy/comfy.script.js#L173-L187

Disable the snippet in the theme config menu located at the profile card dropdown menu.
