### ISSUE TITLE
how to show track number for playlists?

### ISSUE THREAD

**Issue by thaynos** [Comfy-Themes/Spicetify#115]
![image](https://user-images.githubusercontent.com/83282129/216819195-42be0a97-36cc-4429-a462-05519009c6df.png)
it shows normally but with the theme on it doesnt

**Comment by kyrie25** [comment]
Design choice, it's a feature.

**Comment by thaynos** [comment]
Is it possible to have an option that does this? Track numbers are useful
to have.

**Comment by kyrie25** [comment]
@ohitstom ^

**Comment by ohitstom** [comment]
I could probably do that but from a design aspect it might make things cramped af, if I get some time this week I'll have a look.
