### ISSUE TITLE
Full screen color overlay

### ISSUE THREAD

**Issue by 0x5b62656e5d** [Comfy-Themes/Spicetify#118]
If I set the color scheme to Sakura, the pink color overlay will fill the whole screen while in full screen (Spotify default feature). Here's an image: 
![image](https://user-images.githubusercontent.com/112295217/217254225-5cf89173-a850-441e-ad0c-0adf22de1d38.png)

It washes out the song image with pink, and makes the text unreadable, as seen above.

**Comment by ohitstom** [comment]
this seems to be dependant on the color schemes shadow 
![image](https://user-images.githubusercontent.com/22730962/218312584-b9f033dd-056e-408f-910d-3433f848dabb.png)

Not sure how to go about this yet but i'll look into it.

**Comment by ohitstom** [comment]
#116
