### ISSUE TITLE
Implement snippet for removal of lyrics button

### ISSUE THREAD

**Issue by Yashirow** [Comfy-Themes/Spicetify#119]
Hi, the lyrics button isn't disabled like in your screenshot. Everything else is fine. Could it be due to media size ? I currently have a monitor with a low res (1360x768).
![image](https://user-images.githubusercontent.com/100087778/217886027-94fb7434-a510-4ddd-926a-940a408d5c71.png)

**Comment by ohitstom** [comment]
I don't believe this is or has ever been a feature of comfy and was just likely the song in question did not have lyrics. 

I'd be happy to make a simple snippet for it in the open pull request when I get time but I have no estimation for when it will be merged.

**Comment by Yashirow** [comment]
Okay thanks. I use lyrics plus (and I guess most of Spicetify's users use it too) so the button is kinda useless since it redirect to the old lyrics UI.

**Comment by ohitstom** [comment]
#116

**Comment by Yashirow** [comment]
Hi, one of Spotify update broke this snippet.
I guess this value changed `dgwCXe`

**Comment by ohitstom** [comment]
> Hi, one of Spotify update broke this snippet. I guess this value changed `dgwCXe`

Can you send me your version info.

**Comment by Yashirow** [comment]
> > Hi, one of Spotify update broke this snippet. I guess this value changed `dgwCXe`
> 
> Can you send me your version info.

Sorry for the late reply, even though you fixed it here's my version info. Thanks for the quick fix.
![image](https://user-images.githubusercontent.com/100087778/231752628-0432a84d-cd60-4cc7-8e40-5f3386fc605f.png)
