### ISSUE TITLE
Playlist Play Button Is acting wierdly?

### ISSUE THREAD

**Issue by Rajbir98** [Comfy-Themes/Spicetify#130]
![image](https://github.com/Comfy-Themes/Spicetify/assets/84771149/26466af0-a139-4538-a14c-7216cf19f8d6)
![image](https://github.com/Comfy-Themes/Spicetify/assets/84771149/696c3cd7-18d9-40ae-b3af-bc9d8165d38a)
**I'm using the most updated version of Comfy**

**Comment by ohitstom** [comment]
update Spotify

**Comment by Rajbir98** [comment]
will downgrading spicetify work?
i'm using windows 7

**Comment by ohitstom** [comment]
> > update Spotify
> 
> @ohitstom will downgrading spicetify work? i'm using windows 7

im not sure you'll have to test it, but i will not give support for outdated versions im sorry.
