### ISSUE TITLE
Suggestion: round buttons

### ISSUE THREAD

**Issue by thegoldknight** [Comfy-Themes/Spicetify#132]
Hey, thanks for making and maintaining this theme! 

Would it be possible to add round buttons like the original Spotify theme and have a setting to toggle on/off?

Comfy theme
<img width="306" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/dba97cab-0a08-4f61-962f-32503f68d163">
<img width="86" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/43038936-18a3-45aa-9d56-587e20102824">

Original Spotify theme 
<img width="249" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/8b029047-2074-445c-befd-2414694e5d97">
<img width="90" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/30b046e3-991c-438f-a65e-0a5080de580a">

Sorry if this is in the wrong place, I'm new to GitHub.

**Comment by ohitstom** [comment]
I can add an option to set the border radius yes, won't be for a few days since I'm busy though!

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/61e5139f-2799-4751-bec1-9fb8691f0780)
got this so far, will try and finish tonight

**Comment by thegoldknight** [comment]
Hi, 

Thanks for implementing this suggestion.

I do have a question though. Would it be possible to have the artist card on the right sidebar unaffected by the border radius? 

Button Radius at 8
<img width="322" alt="Screenshot 2023-06-05 at 10 36 12 AM" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/9d72eb7a-207f-4bce-b65a-4c1f0b759f7a">

Button Radius at 50
<img width="317" alt="Screenshot 2023-06-05 at 10 33 03 AM" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/0f118170-4b77-43a3-8ad8-24542f016933">

**Comment by ohitstom** [comment]
ah yeah, sadly my approach is less than perfect, will add that class as an exception let me know on the discord if you find anymore

**Comment by thegoldknight** [comment]
I found some exceptions but I don't have discord so I'll put them here instead.

The corners of the words in the artist description in the right sidebar are cut off
<img width="308" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/3aa77132-8650-4d30-a936-4da7f5d40a65">

This one idk whether to add this as an issue here or in the Beautiful Lyrics github, but the button radius affects the word borders in the new Beautiful Lyrics page as well. 
<img width="640" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/5e0958dd-18fb-450b-867b-1014b3130cd6">

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/26dde348-474e-405d-b86a-8b1154c71cee)
i cant seem to recreate?

**Comment by thegoldknight** [comment]
> ![image](https://user-images.githubusercontent.com/22730962/251964399-26dde348-474e-405d-b86a-8b1154c71cee.png)
> i cant seem to recreate?

Set button radius to 50
sorry for the late response
