### ISSUE TITLE
wal16 theme missing progress bar 

### ISSUE THREAD

**Issue by thegoldknight** [Comfy-Themes/Spicetify#134]
<img width="1440" alt="Screenshot 2023-06-06 at 11 31 44 AM" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/0878b324-be50-4440-b123-1c0535d6b500">

it also still displays whatever theme you were using last when you change it 
<img width="176" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/b14fcd4d-f691-432d-be78-621bf909f1f1">

**Comment by kyrie25** [comment]
wal16 is meant to be used with the CLI as it fetches color from your operating system.
