### ISSUE TITLE
Top part of playlist cover cut off

### ISSUE THREAD

**Issue by thegoldknight** [Comfy-Themes/Spicetify#138]
Top part of playlist cover is cut off
<img width="505" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/3acaf8ba-f8b9-42de-9cc9-9dce900c728a">
also on albums:
<img width="396" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/2e028009-0d57-4ad8-b604-f600a845802a">

**Comment by ohitstom** [comment]
can you send your config

**Comment by thegoldknight** [comment]
the config-xpui.ini?

[Setting]
prefs_path              = /Users/<redacted>/Library/Application Support/Spotify/prefs
color_scheme            = Comfy
overwrite_assets        = 1
spotify_path            = /Applications/Spotify.app/Contents/Resources
current_theme           = Comfy
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
inject_theme_js         = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = popupLyrics.js|bookmark.js|shuffle+.js
custom_apps           = marketplace|stats|better-local-files|new-releases|lyrics-plus
sidebar_config        = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.13.661.ga588f749
with    = 2.20.0

**Comment by thegoldknight** [comment]
Nevermind, I manually reinstalled comfy and it fixed it

**Comment by ohitstom** [comment]
> Nevermind, I manually reinstalled comfy and it fixed it

weird, was gonna check it out at some point today so I'll let you know

**Comment by thegoldknight** [comment]
I'm having some crazy things happening with my spicetify so I wouldn't be surprised if it's just my end.
