### ISSUE TITLE
Comfy settings not opening

### ISSUE THREAD

**Issue by TheGeeKing** [Comfy-Themes/Spicetify#144]
Since spicetify 2.22.1, clicking on the comfy settings icon doesn't open the settings menu anymore.

I get that from the console:
![image](https://github.com/Comfy-Themes/Spicetify/assets/58857539/670f7626-18e0-4600-8414-da00669a42d6)

**Comment by ohitstom** [comment]
The latest version of Spotify .17 broke our panels, I've pushed a fix for the styling, however this cant be fixed until a new Spicetify version is released to fix this.

Once Spicetify is updated it should be good to go straight away but nothing i can do until then...
