### ISSUE TITLE
Theme settings menu automatically closing.

### ISSUE THREAD

**Issue by GavingPiper** [Comfy-Themes/Spicetify#145]
When installed through the Spicetify marketplace the theme setting gear does not open theme settings. Double-clicking the bag briefly causes the side panel to open showing a large black bar, then closing itself around .2 seconds after. 

I'll be happy to respond with any more info on the issue, sorry if I didn't articulate the issue well.
[Video of issue](https://clipchamp.com/watch/22CYqSG9fdr)

**Comment by ohitstom** [comment]
dupe of #144
