### ISSUE TITLE
NCS Visualizer not working with Comfy non-legacy

### ISSUE THREAD

**Issue by AxaliaN** [Comfy-Themes/Spicetify#146]
As the title says, the app NCS Visualizer (https://github.com/Konsl/spicetify-ncs-visualizer) is not working with this theme. It works on all other themes I checked, so it would seem it is an issue with this theme. Could you please check it out since Comfy is my fav theme 😢

**Comment by ohitstom** [comment]
i don't see why that would be affected, since if it was an issue with our theme it would be JavaScript related @kyrie25 could you check it out when you get time please 🙏

**Comment by kyrie25** [comment]
> i don't see why that would be affected, since if it was an issue with our theme it would be JavaScript related @kyrie25 could you check it out when you get time please 🙏

Don't think the extension handles anything more than settings and background image though so no idea, low priority anyway.

**Comment by AxaliaN** [comment]
The dev of https://github.com/Konsl/spicetify-ncs-visualizer fixed it on their end, this can be closed!

**Comment by ohitstom** [comment]
Ah, i see what the issue was based on his commit.
I should have investigated how his extension works, we mess with the main views positioning more than we should which caused the issue, glad he manage to fix it on his end!
