### ISSUE TITLE
Add support for topbar inside titlebar for macOS 

### ISSUE THREAD

**Issue by thegoldknight** [Comfy-Themes/Spicetify#147]
<img width="1398" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/135397968/b4179e50-8247-4468-b77b-550881cd7728">
At the moment, the window controls cover the back and forward buttons.

**Comment by ohitstom** [comment]
don't suppose you have some css knowledge and could make a pr yourself? I don't have a Mac so I really don't know how I would do this reliably without just guessing, if not I'll do the latter but yeah
