### ISSUE TITLE
How can I change the color of the progress bar?

### ISSUE THREAD

**Issue by Rajdave69** [Comfy-Themes/Spicetify#148]
I would like to make 2 modifications to the theme for myself, how do I go about doing it?

1. Change the color of the progress bar while playing a song, green doesn't match the blue background IMO.
2. Increase the padding of the total song total song duration thing and the current song progress counter thing (look at image)
![image](https://github.com/Comfy-Themes/Spicetify/assets/86198810/31db90c0-aa5d-474d-8b12-923ad3540505)

How can I go about doing this?

**Comment by Rajdave69** [comment]
nvm sorry i found out

**Comment by ohitstom** [comment]
glad you figured it out but why would you want more padding 🗿

**Comment by Rajdave69** [comment]
the time counter thing looks like it's too close to the progress bar, I wanted it to be 1-2 pixels higher
