### ISSUE TITLE
Albums & Playlist overlapping with page footer

### ISSUE THREAD

**Issue by Davoleo** [Comfy-Themes/Spicetify#149]
- This seems to happen both on playlists and albums
- I've installed the theme via marketplace 
![image](https://github.com/Comfy-Themes/Spicetify/assets/24458276/42b72cff-fdb3-45dc-bd91-e371b28929f8)

Versions: 
Spotify: 1.2.20.1218.g02aff7a4
Spicetify: v2.23.2
Spicetify Marketplace: 0.8.9

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/c1d7856a-7424-43d3-a8de-616600ad6567)
i dont have this issue you likely have something installed that is messing with it, without more info i cannot help you.

**Comment by Davoleo** [comment]
you're right, i had a patch in place that was breaking spacing, since I had another theme installed before;
Sorry for the pointless issue.
