### ISSUE TITLE
lost setting button

### ISSUE THREAD

**Issue by NhomNhom0** [Comfy-Themes/Spicetify#150]
![image](https://github.com/Comfy-Themes/Spicetify/assets/117582310/66988e66-ea69-4943-b985-5c7070e918be)

the setting button lost after i update my spotify, and re-install spicetify

**Comment by ohitstom** [comment]
what's your versions

**Comment by ohitstom** [comment]
https://github.com/spicetify/spicetify-cli/pull/2573

you need to wait for this to be merged and a spicetify release, or downgrade spotify in the meantime.,

**Comment by NhomNhom0** [comment]
> what's your versions

my spotify version is  1.2.21.1104.g42cf0a50
