### ISSUE TITLE
dialog screens too bright

### ISSUE THREAD

**Issue by dxcvvxd** [Comfy-Themes/Spicetify#151]
this is kinda bright compared to the rest of the theme, is there a way to change it?
![image](https://github.com/Comfy-Themes/Spicetify/assets/77129815/ec220c83-4cf9-433d-8081-7704cd12bdcc)

**Comment by ohitstom** [comment]
what color scheme is this?

**Comment by ohitstom** [comment]
what color scheme is this?

**Comment by ohitstom** [comment]
what color scheme is this?

**Comment by dxcvvxd** [comment]
it is the yami variant, i dont know if spicetify does this wrong.

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/16726556-e01c-4d98-9f70-10f13135e757)
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/d13c7b10-a968-4dd9-8c8b-b1eddecd187b)

**Comment by dxcvvxd** [comment]
im not talking about the modal dialogues, i mean the overlay behind it
![image](https://github.com/Comfy-Themes/Spicetify/assets/77129815/2cbff107-dedd-4e13-a703-05a8fe92547b)

**Comment by ohitstom** [comment]
oh, not really unless you modify the colorscheme, it's based off the shadow color

**Comment by ohitstom** [comment]
uninstall from marketplace, run our local install script, go to appdata spicetify themes comfy, open your colorini find yami and chanhe the shadow hex
