### ISSUE TITLE
Spotify stock color scheme

### ISSUE THREAD

**Issue by zeroma25** [Comfy-Themes/Spicetify#152]
Could you please add a color scheme like in stock Spotify?
For example, like this:

```
[Spotify]
text=D4D4D4
subtext=b3b3b3
main=121212
main-transition=121212
sidebar=000000
player=121212
card=232323
button=1DB954
buttonActive=1ED760
buttonDisabled=535353
notification=4687D6
notificationError=E22134
shadow=000000
selected-row=DEDEDE
tabActive=333333
playbackBar=DEDEDE
misc=535353
heart=1DB954
progress-fg=1DB954
progress-bg=636363
play-button=1DB954
play-button-active=1DB954
radio-btn-active=1DB954
pagelink-active=333333
``` 
Or your own version.

**Comment by ohitstom** [comment]
can do, can't promise how soon I'm in the middle of rewriting the settings menu so maybe half a week to a week?

**Comment by zEROma25** [comment]
OK thanks!

**Comment by ohitstom** [comment]
```
[Spotify]
main-transition=121212
heart=1DB954
progress-fg=1DB954
progress-bg=636363
play-button=1DB954
play-button-active=1DB954
radio-btn-active=1DB954
pagelink-active=333333
```

probably going to be like this, fill out our custom ones, let spotify handle their own.
Not going to make it the default color scheme but it will be near the top once i get time.

**Comment by ohitstom** [comment]
sorry im dumb that wont work if you enable it in the settings menu it'll only work locally or in marketplace, feel free to use it like that in the meantime though

**Comment by zEROma25** [comment]
> it'll only work locally or in marketplace, feel free to use it like that in the meantime though

Thanks a lot, it's great!
