### ISSUE TITLE
pause/play button design

### ISSUE THREAD

**Issue by bis-marck** [Comfy-Themes/Spicetify#154]
Hi, just a very minor issue. The pause/play button design is incomplete.
![Screenshot 2023-11-09 153228](https://github.com/Comfy-Themes/Spicetify/assets/150327624/8eda9c26-b528-4fba-ba7a-03baadaefed9)

I also have another question. I tried editing the color values in color.ini but nothing's happening. Is there an extra step to do?

**Comment by ohitstom** [comment]
you have the extensions from other themes enabled
