### ISSUE TITLE
Search bar won't appear in the title bar of spotify

### ISSUE THREAD

**Issue by ianrispin** [Comfy-Themes/Spicetify#155]
Spicetify v2.27.0
Spotify v1.2.24.756.g7a7fc7f0
MacOS Ventura 13.5.2

I can't get the search bar to appear in the title bar of spotify.
![image](https://github.com/Comfy-Themes/Spicetify/assets/50210259/50038b73-1e42-498e-a909-c885aa9c5aa1)

For reference, this is what I'm referring to:
![Screenshot 2023-11-11 at 3 35 29 PM](https://github.com/Comfy-Themes/Spicetify/assets/50210259/d8490705-d8ee-4d78-b4cd-03d9a81b670b)

I've tried messing with every option in the comfy settings, but it just doesn't show up. I'm running the latest version of comfy (just updated yesterday), but this has been the case for several months.

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/3953f113-a833-4eb9-8592-1e2988b85e2d)
