### ISSUE TITLE
Slider snippet callback only executing on manual toggle

### ISSUE THREAD

**Issue by dxcvvxd** [Comfy-Themes/Spicetify#158]
https://github.com/Comfy-Themes/Spicetify/assets/77129815/70da41c3-caf9-49ee-bbfc-2db53a9650ff

**Comment by ohitstom** [comment]
haven't experienced this, gonna need more info to troubleshoot and console logs

**Comment by dxcvvxd** [comment]
version:
spotify/spicetify - latest
theme - latest
logs: idk how to check them, would like more info on that thanks
config:
```{"Color-Scheme":"Yami","Scheme-Features":"Select an option","Flatten-Colors":"normal","Dark-Modals":"dark","App-Title":"","Button-Radius":"","Custom-Font":false,"Home-Header-Snippet":false,"Home-Header-Color":"","Topbar-Inside-Titlebar-Snippet":true,"Horizontal-pageLinks-Snippet":true,"visible-column-bar-Snippet":false,"Tracklist-Gradient-Height":"","Hoverable-Timers-Snippet":false,"Remove-Device-Picker-Notification-Snippet":true,"Remove-Progress-Bar-Gradient-Snippet":false,"Remove-Lyrics-Button-Snippet":false,"Custom-Cover-Art-Dimensions":true,"Right-Art-Snippet":false,"Image-Blur":"8","Apple-Music-Gradient-Snippet":false,"Custom-Image":false,"Color-Schemes":{"Comfy":{"text":"FFFFFF","subtext":"B9BBBE","main":"23283D","main-elevated":"32364A","main-transition":"1E2233","highlight":"45495B","highlight-elevated":"383D50","sidebar":"1E2233","player":"101320","card":"101320","shadow":"1E2233","selected-row":"F1F1F1","button":"7289DA","button-active":"5C6FB1","button-disabled":"4B588C","tab-active":"1E2233","notification":"7289DA","notification-error":"D25050","misc":"000000","play-button":"7289DA","play-button-active":"869ADF","progress-fg":"1ED760","progress-bg":"7289DA","heart":"D25050","pagelink-active":"5C6EB1","radio-btn-active":"7289DA"},"Spotify":{"text":"FFFFFF","subtext":"B3B3B3","main":"121212","main-elevated":"242424","main-transition":"000000","highlight":"1A1A1A","highlight-elevated":"2A2A2A","sidebar":"000000","player":"181818","card":"282828","shadow":"000000","selected-row":"FFFFFF","button":"1DB954","button-active":"1ED760","button-disabled":"535353","tab-active":"333333","notification":"4687D6","notification-error":"E22134","misc":"7F7F7F","play-button":"1DB954","play-button-active":"1DB954","progress-fg":"1DB954","progress-bg":"636363","heart":"1DB954","pagelink-active":"333333","radio-btn-active":"1DB954"},"Nord":{"text":"B2BCCC","subtext":"B2BCCC","main":"2E3440","main-elevated":"3C414C","main-transition":"262B35","highlight":"50555F","highlight-elevated":"424852","sidebar":"262B35","player":"2E3440","card":"363D4C","shadow":"1D2128","selected-row":"B2BCCC","button":"8A99AF","button-active":"718CAD","button-disabled":"434C5E","tab-active":"363D4C","notification":"363D4C","notification-error":"A9555E","misc":"FFFFFF","play-button":"8A99AF","play-button-active":"718CAD","progress-fg":"8A99AF","progress-bg":"4B566A","heart":"718CAD","pagelink-active":"B7C1D5","radio-btn-active":"363D4C"},"Kitty":{"text":"FFFFFF","subtext":"FFDDDC","main":"C94985","main-elevated":"CD548C","main-transition":"DE4B90","highlight":"DE4B90","highlight-elevated":"CF598D","sidebar":"E072A6","player":"941550","card":"DE5BA5","shadow":"2B0718","selected-row":"FFDDDC","button":"941550","button-active":"FFFFFF","button-disabled":"941550","tab-active":"E072A6","notification":"E072A6","notification-error":"994B6F","misc":"000000","play-button":"FFFFFF","play-button-active":"A13267","progress-fg":"DE4B90","progress-bg":"994B6F","heart":"A13267","pagelink-active":"DE4B90","radio-btn-active":"994B6F"},"Lunar":{"text":"F3F3F3","subtext":"CECECE","main":"161616","main-elevated":"232323","main-transition":"101010","highlight":"2A2A2A","highlight-elevated":"292929","sidebar":"202020","player":"161616","card":"303030","shadow":"252525","selected-row":"CECECE","button":"3281EA","button-active":"0284E8","button-disabled":"303030","tab-active":"EBBCBA","notification":"3281EA","notification-error":"B10C0C","misc":"252525","play-button":"EBBCBA","play-button-active":"EBA9A7","progress-fg":"025CA1","progress-bg":"202020","heart":"EBBCBA","pagelink-active":"FFFFFF","radio-btn-active":"0284E8"},"Deep":{"text":"4F9A87","subtext":"406560","main":"040614","main-elevated":"0A111D","main-transition":"0F111A","highlight":"0F1F28","highlight-elevated":"0C1520","sidebar":"0F111A","player":"040614","card":"0F1118","shadow":"0F1118","selected-row":"4F9A87","button":"106165","button-active":"4F9A87","button-disabled":"0C1C19","tab-active":"0A1527","notification":"051024","notification-error":"051024","misc":"406560","play-button":"106165","play-button-active":"4F9A87","progress-fg":"4F9A87","progress-bg":"106165","heart":"D25050","pagelink-active":"4F9A87","radio-btn-active":"106165"},"Velvet":{"text":"AD434E","subtext":"762F37","main":"1E1E1E","main-elevated":"272021","main-transition":"161616","highlight":"322324","highlight-elevated":"2A2122","sidebar":"161616","player":"080808","card":"0F0F0F","shadow":"161616","selected-row":"973B45","button":"6B2B32","button-active":"552328","button-disabled":"262626","tab-active":"161616","notification":"6B2B32","notification-error":"60272D","misc":"000000","play-button":"552328","play-button-active":"6B2B32","progress-fg":"81333B","progress-bg":"A23F49","heart":"60272D","pagelink-active":"4A1F23","radio-btn-active":"6B2B32"},"Yami":{"text":"D4D4D4","subtext":"D4D4D4","main":"0A0A10","main-elevated":"0D0D14","main-transition":"0A0A10","highlight":"191923","highlight-elevated":"0E0E15","sidebar":"0A0A10","player":"0A0A10","card":"191923","shadow":"AF8BF3","selected-row":"353447","button":"D4D4D4","button-active":"353447","button-disabled":"111117","tab-active":"191923","notification":"0A0A10","notification-error":"F7407B","misc":"0A0A10","play-button":"2B2A3D","play-button-active":"353447","progress-fg":"F7407B","progress-bg":"0A0A10","heart":"F7407B","pagelink-active":"F7407B","radio-btn-active":"191923"},"catppuccin-latte":{"text":"4C4F69","subtext":"5C5F77","main":"E6E9EF","main-elevated":"DCE0E6","main-transition":"E6E9EF","highlight":"CED3DB","highlight-elevated":"D8DBE3","sidebar":"EFF1F5","player":"E6E9EF","card":"BCC0CC","shadow":"E6E9EF","selected-row":"5C5F77","button":"1E66F5","button-active":"209FB5","button-disabled":"BCC0CC","tab-active":"D20F39","notification":"1E66F5","notification-error":"D20F39","misc":"ACB0BE","play-button":"EA76CB","play-button-active":"DD7878","progress-fg":"04A5E5","progress-bg":"BCC0CC","heart":"FE640B","pagelink-active":"FFFFFF","radio-btn-active":"209FB5"},"catppuccin-frappe":{"text":"C6D0F5","subtext":"B5BFE2","main":"292C3C","main-elevated":"333648","main-transition":"292C3C","highlight":"3B4058","highlight-elevated":"373B4D","sidebar":"303446","player":"292C3C","card":"51576D","shadow":"626880","selected-row":"B5BFE2","button":"8CAAEE","button-active":"85C1DC","button-disabled":"51576D","tab-active":"E78284","notification":"8CAAEE","notification-error":"E78284","misc":"626880","play-button":"F4B8E4","play-button-active":"EECEBE","progress-fg":"99D1DB","progress-bg":"51576D","heart":"EF9F76","pagelink-active":"FFFFFF","radio-btn-active":"85C1DC"},"catppuccin-macchiato":{"text":"CAD3F5","subtext":"B8C0E0","main":"181926","main-elevated":"232533","main-transition":"181926","highlight":"333645","highlight-elevated":"292A39","sidebar":"24273A","player":"181926","card":"494D64","shadow":"5B6078","selected-row":"B8C0E0","button":"8AADF4","button-active":"7DC4E4","button-disabled":"494D64","tab-active":"ED8796","notification":"8AADF4","notification-error":"ED8796","misc":"5B6078","play-button":"F5BDE6","play-button-active":"F0C6C6","progress-fg":"91D7E3","progress-bg":"494D64","heart":"F5A97F","pagelink-active":"FFFFFF","radio-btn-active":"7DC4E4"},"catppuccin-mocha":{"text":"CDD6F4","subtext":"BAC2DE","main":"181825","main-elevated":"232432","main-transition":"181825","highlight":"333645","highlight-elevated":"292A38","sidebar":"1E1E2E","player":"181825","card":"45475A","shadow":"585B70","selected-row":"BAC2DE","button":"89B4FA","button-active":"74C7EC","button-disabled":"45475A","tab-active":"F38BA8","notification":"89B4FA","notification-error":"F38BA8","misc":"585B70","play-button":"F5C2E7","play-button-active":"F2CDCD","progress-fg":"89DCEB","progress-bg":"45475A","heart":"FAB387","pagelink-active":"FFFFFF","radio-btn-active":"74C7EC"},"rose-pine":{"text":"E0DEF4","subtext":"908CAA","main":"1F1D2E","main-elevated":"2D2B3C","main-transition":"26233A","highlight":"403D52","highlight-elevated":"333142","sidebar":"191724","player":"1F1D2E","card":"403D52","shadow":"524F67","selected-row":"E0DEF4","button":"EBBCBA","button-active":"EBBCBA","button-disabled":"6E6A86","tab-active":"524F67","notification":"9CCFD8","notification-error":"EB6F92","misc":"FFFFFF","play-button":"EBBCBA","play-button-active":"EBBCBA","progress-fg":"EBBCBA","progress-bg":"403D52","heart":"EB6F92","pagelink-active":"EBBCBA","radio-btn-active":"9CCFD8"},"rose-pine-moon":{"text":"E0DEF4","subtext":"908CAA","main":"2A273F","main-elevated":"37344C","main-transition":"393552","highlight":"44415A","highlight-elevated":"3D3A52","sidebar":"232136","player":"2A273F","card":"44415A","shadow":"56526E","selected-row":"E0DEF4","button":"EA9A97","button-active":"EA9A97","button-disabled":"6E6A86","tab-active":"56526E","notification":"9CCFD8","notification-error":"EB6F92","misc":"FFFFFF","play-button":"EA9A97","play-button-active":"EA9A97","progress-fg":"EA9A97","progress-bg":"44415A","heart":"EB6F92","pagelink-active":"EA9A97","radio-btn-active":"9CCFD8"},"rose-pine-dawn":{"text":"575279","subtext":"797593","main":"FFFAF3","main-elevated":"F3EEEB","main-transition":"F2E9E1","highlight":"DFDAD9","highlight-elevated":"EEE9E6","sidebar":"FAF4ED","player":"FFFAF3","card":"DFDAD9","shadow":"FAF4ED","selected-row":"575279","button":"D7827E","button-active":"D7827E","button-disabled":"9893A5","tab-active":"CECACD","notification":"56949F","notification-error":"B4637A","misc":"FFFFFF","play-button":"D7827E","play-button-active":"D7827E","progress-fg":"D7827E","progress-bg":"DFDAD9","heart":"B4637A","pagelink-active":"D7827E","radio-btn-active":"907AA9"},"Mono":{"text":"FFFFFF","subtext":"B9BBBE","main":"171717","main-elevated":"262626","main-transition":"FFFFFF","highlight":"3B3B3B","highlight-elevated":"2E2E2E","sidebar":"101010","player":"171717","card":"343434","shadow":"595858","selected-row":"F1F1F1","button":"FFFFFF","button-active":"C5C5C5","button-disabled":"4A4949","tab-active":"303030","notification":"101010","notification-error":"D25050","misc":"000000","play-button":"FFFFFF","play-button-active":"FFFFFF","progress-fg":"FFFFFF","progress-bg":"343434","heart":"FFFFFF","pagelink-active":"787878","radio-btn-active":"737373"},"Sunset":{"text":"FFCE3F","subtext":"FEF3BB","main":"171717","main-elevated":"272622","main-transition":"000000","highlight":"3D3C32","highlight-elevated":"2F2E28","sidebar":"101010","player":"171717","card":"CC9756","shadow":"E3B47B","selected-row":"FEF3BB","button":"FFCE3F","button-active":"BF9B30","button-disabled":"4A4949","tab-active":"303030","notification":"FFFFFF","notification-error":"D25050","misc":"000000","play-button":"FFCE3F","play-button-active":"FC9E3A","progress-fg":"FF8300","progress-bg":"343434","heart":"FF8300","pagelink-active":"FEF3BB","radio-btn-active":"FEF3BB"},"Neon":{"text":"588BAE","subtext":"EAFFFF","main":"171717","main-elevated":"262626","main-transition":"000000","highlight":"3B3B3B","highlight-elevated":"2E2E2E","sidebar":"101010","player":"171717","card":"7FA1B5","shadow":"A9C9DB","selected-row":"F1F1F1","button":"588BAE","button-active":"3B5D75","button-disabled":"4A4949","tab-active":"303030","notification":"FFFFFF","notification-error":"D25050","misc":"000000","play-button":"588BAE","play-button-active":"5085AB","progress-fg":"00AFDB","progress-bg":"343434","heart":"00AFDB","pagelink-active":"BBE7FE","radio-btn-active":"EAFFFF"},"Forest":{"text":"B2C5B3","subtext":"D5DDDE","main":"171717","main-elevated":"262626","main-transition":"000000","highlight":"3B3B3B","highlight-elevated":"2E2E2E","sidebar":"101010","player":"171717","card":"5C6E59","shadow":"3C5148","selected-row":"F1F1F1","button":"B2C5B3","button-active":"F1F1F1","button-disabled":"4A4949","tab-active":"303030","notification":"FFFFFF","notification-error":"D25050","misc":"000000","play-button":"3C5148","play-button-active":"43705D","progress-fg":"3C5148","progress-bg":"343434","heart":"3C5148","pagelink-active":"3C5148","radio-btn-active":"737373"},"Sakura":{"text":"FCB4CA","subtext":"FFDCDC","main":"171717","main-elevated":"262626","main-transition":"000000","highlight":"3D3838","highlight-elevated":"2E2E2E","sidebar":"101010","player":"171717","card":"D68BA2","shadow":"FCB4CA","selected-row":"FFDCDC","button":"FCB4CA","button-active":"D48AA0","button-disabled":"4A4949","tab-active":"303030","notification":"FFFFFF","notification-error":"D25050","misc":"000000","play-button":"F42C38","play-button-active":"BA182B","progress-fg":"CFEEFA","progress-bg":"343434","heart":"F25477","pagelink-active":"F5BCDB","radio-btn-active":"FFDCDC"},"Vaporwave":{"text":"01CDFE","subtext":"EAFFFF","main":"171717","main-elevated":"262626","main-transition":"000000","highlight":"3B3B3B","highlight-elevated":"2E2E2E","sidebar":"101010","player":"171717","card":"007F9E","shadow":"2EC2E6","selected-row":"F1F1F1","button":"01CDFE","button-active":"118BA8","button-disabled":"4A4949","tab-active":"303030","notification":"FFFFFF","notification-error":"D25050","misc":"000000","play-button":"FFD300","play-button-active":"E3C01B","progress-fg":"F706CF","progress-bg":"343434","heart":"F706CF","pagelink-active":"C0D6FA","radio-btn-active":"EAFFFF"}},"Font":"","Custom-Font-Collapsed":false,"Home-Header-Snippet-Collapsed":false,"Cover-Art-Width":"122","Cover-Art-Height":"122","Cover-Art-Radius":"10","Cover-Art-Bottom":"45"}```
extensions and stuff:
local: lyricsplus, endlessjukebox, marketplace itself
marketplace ones: aoty score viewer, adblock, fullappdisplay,seek on scroll, spotify genres, image opener, no tracking links, anonymized radios, autoplay
snippets: hide upgrade button, remove connect bar, fix main view width, disable homepage recommendations, fix liked button, remove recently played, pretty lyrics, hide now playing view, hide podcast tab, fullscreen hide next something, hide recent searches.

also id like to add that it worked normally and randomly stopped maybe because of an update and i noticed it about a week ago

**Comment by ohitstom** [comment]
>also id like to add that it worked normally and randomly stopped maybe because of an update and i noticed it about a week ago
is this before or after the settings menu redesign

**Comment by dxcvvxd** [comment]
ok so a quick update: its fixed now
i dont know if you've done anything but i havent either and it just works now, not sure what has caused it still

**Comment by ohitstom** [comment]
I've been busy recently but when I tried to recreate the issue on my end I was unable to. try running spicetify enable-devtools, when Spotify loads open inspect element and go to the console tab, enable verbose logs in the top right drop-down, hit Ctrl r to reload, and send a vid of that + whenever you toggle on or off the option or any errors

**Comment by ohitstom** [comment]
If you would like to get in contact over discord and sort out a voice call so i can go through some debugging steps with you that would be great, you are welcome to not talk but i'll need to so i can guide you obviously!

**Comment by dxcvvxd** [comment]
yeah sure, i can do that
if you're free just text me over at @dxcvvxd in discord
