### ISSUE TITLE
 Microsoft's Fluent Design System theme

### ISSUE THREAD

**Issue by Ox3rror** [Comfy-Themes/Spicetify#159]
**Is your feature request related to a problem? Please describe.**
 I preferMicrosoft's Fluent Design System, is it possible get a theme like this : https://github.com/nimsandu/spicetify-bloom. I love when i click on lyrics it give me fluent background and animation. 
![dark](https://github.com/Comfy-Themes/Spicetify/assets/132026922/3559f863-4fb5-4851-b7f4-d462f7fee0eb)

Also, Thanks for this Spicetify theme.

**Comment by ohitstom** [comment]
can you elaborate? comfys design doesnt really look anything similar, i also think fluent/bloom uses alot of js to achieve its effects and not css which i will not implement. 

maybe im misunderstanding you though

**Comment by Ox3rror** [comment]
I was talking about, is it possible to make any fluent/minimal theme. Oh, if you will not use any js, i am closing this issue.

**Comment by ohitstom** [comment]
> I was talking about, is it possible to make any fluent/minimal theme. Oh, if you will not use any js, i am closing this issue.

my apologies!
