### ISSUE TITLE
Spotify Connect popup and controls look really strange 

### ISSUE THREAD

**Issue by forever-and-a-day** [Comfy-Themes/Spicetify#161]
To reproduce the bug, please play music on a different device (like a phone) at the same time that the desktop app is in use. 
**Environment**
- Spotify Version: `Spotify for macOS (Apple Silicon) 1.2.25.1011.g0348b2ea`
- Spicetify Version: `Spicetify v2.25.0`
- Platform (WIN, MAC, LINUX): `MAC`

**Addons**
- Extensions: `[playNextWrapper.js, spotifyGenres.js, full-queue-clear.js, utilities.js, theme.js]`
- Custom Apps: `[marketplace, combined-playlists]`
- Snippets: `[]`

**Spicetify Config**
System username censored for privacy reasons. 
My browser detects this as a virus when trying to download it. **There is no executable code in the ini file, just the spicetify config file.**
https://files.catbox.moe/6rkypt.ini

**Theme Information**
https://files.catbox.moe/w822pw.txt
- Installed via Marketplace Or CLI: `Marketplace`

**Describe the bug**
The icon on the spotify connect bubble is too big (pushes connected device name out of the bubble), and the controls popout has icons that are too big and obscure information

**Screenshots**
Device name censored for privacy reasons. 
![Screen Shot 2023-11-30 at 11 13 58 AM](https://github.com/Comfy-Themes/Spicetify/assets/10383240/c7e175ac-c36f-4093-b823-d6e1ae774512)
<img width="356" alt="Screen Shot 2023-11-30 at 11 14 16 AM" src="https://github.com/Comfy-Themes/Spicetify/assets/10383240/6b9aea1f-5601-4c9d-bb55-f637b5b0156d">

Please also provide devtools errors/debug messages if possible:
https://files.catbox.moe/9x1fue.txt

**Comment by ohitstom** [comment]
your spicetify is super out of date, i fixed this in a spicetify release a few versions ago, please run spicetify upgrade
