### ISSUE TITLE
catppubbin tab-active does not follow WCAG guidelines

### ISSUE THREAD

**Issue by yhkhoo** [Comfy-Themes/Spicetify#162]
(from https://discord.com/channels/811203761619337259/1172158176360140910, sorry for the delay)
**Is your feature request related to a problem? Please describe.**
The tab-active color looks awful on all 4 Catppuccin colorschemes. It is a bright red, which firstly gives horrible contrast with the text, and secondly looks glaring compared to everything else.
Here is a screenshot of how it looks (using the macchiato flavour, but it is a problem on all 4 Catppuccin flavours)
![comfy1](https://github.com/Comfy-Themes/Spicetify/assets/77189596/57f1e55d-1f5f-4baa-b829-48c4f77b11cc)
For comparison, this is how the official Catppuccin Spotify theme does it.
![catppuccin1](https://github.com/Comfy-Themes/Spicetify/assets/77189596/93d0986d-d358-4963-ace8-30fbe275f1f9)

**Describe the solution you'd like**
Change it to a grey color instead.
This is what it looks like using `surface1` of the palette, which matches the `button-disabled` color
![comfysurface1](https://github.com/Comfy-Themes/Spicetify/assets/77189596/537b2186-3597-4bfb-a7b3-8d8fa40e95f3)

**Describe alternatives you've considered**
editing my `color.ini`

**Additional context**

**Comment by ohitstom** [comment]
i will look into matching the official catppuccin implementation, which funnily enough i implemented xd
