### ISSUE TITLE
Apple Music Gradient for Playlists

### ISSUE THREAD

**Issue by spigglez** [Comfy-Themes/Spicetify#164]
Can you add the Apple Music Gradient Feature but instead of the song playing it shows the playlist cover of the playlist page you are currently on (even if not currently playing a song from it)?

**Comment by ohitstom** [comment]
im confused as to what you mean, can you give me a link to the playlist in question?

**Comment by ohitstom** [comment]
i will need to close this in a week if i dont get further elaboration
