### ISSUE TITLE
move topbar inside titlebar breaks drop down in queue

### ISSUE THREAD

**Issue by IMrCreepyI** [Comfy-Themes/Spicetify#166]
**Environment**
- Spotify Version: 1.2.25.1011.g0348b2ea
- Spicetify Version: v2.28.0
- Platform (WIN, MAC, LINUX): WIN

**Theme Information**
- Installed via Marketplace Or CLI: Marketplace

**Describe the bug**
when having "move topbar inside titlebar" enabled it breaks the drop down in queue not allowing you to switch to recently played

**Screenshots**
![image](https://github.com/Comfy-Themes/Spicetify/assets/106611607/146efa8b-780f-4a00-9dc6-4480e73fbe53)
![image](https://github.com/Comfy-Themes/Spicetify/assets/106611607/37561751-8b28-4a7b-a8ce-a8f531182f58)

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/22add52f-6bb3-4d43-aa5d-00d0036d7ec2)
this is actually a spotify issue, if you disable our theme and shrink your window size you'll see the dropdown does not render
