### ISSUE TITLE
Disable custom bar

### ISSUE THREAD

**Issue by 0xSnoxzy** [Comfy-Themes/Spicetify#169]
Hello, i just installed your theme from the spicetify marketplace, and was wondering if there was a toggle for the custom player bar but couldn't find any, it would be a nice option for someone like me that like to stick with the default spotify bar. thank you in advance :)

**Comment by ohitstom** [comment]
I doubt this is something we can consider I'm afraid, I'll give it a shot and see if it affects any other parts of the theme which it is highly likely it might.

If it doesn't effect anything else (eg we wouldn't have to consider this option any time we want to implement something new), then I'd be happy too.

I'll keep you posted!

**Comment by 0xSnoxzy** [comment]
perfect, thank you again.
