### ISSUE TITLE
additional banner options

### ISSUE THREAD

**Issue by 0coins** [Comfy-Themes/Spicetify#172]
**Is your feature request related to a problem? Please describe.**
When viewing an album/playlist, the banner image is the cover of the song I'm currently listening to. 

**Describe the solution you'd like**
I'd like an option to change the banner image back to Spotify's original gradient of the playlist/album's cover art. 

**Additional context**
this is what it looks like:
![image](https://github.com/Comfy-Themes/Spicetify/assets/80586452/49bc2f73-1842-4e31-a760-29ad3909234f)

this is what i'd like it to look:
![image](https://github.com/Comfy-Themes/Spicetify/assets/80586452/30779fe0-2b67-46ee-9ed7-2420ddd66740)

**Comment by ohitstom** [comment]
pushing a commit to fix it now, probably gonna keep this issue open until you've had a chance to test it since this makes the codespace like 10x worse lmao

**Comment by 0coins** [comment]
it works just as i want it to based on the settings i already have. thank youuuu..
