### ISSUE TITLE
Missing themes in the Spicetify Marketplace

### ISSUE THREAD

**Issue by JustSxm** [Comfy-Themes/Spicetify#173]
**Environment**
- Spotify Version: 1.2.26.1187.g36b715a1
- Spicetify Version: v2.30.0
- Platform (WIN, MAC, LINUX): WIN

**Addons**
*`[name1, name2]` or `[]` if none*
- Extensions: `placeholder`
- Custom Apps: `placeholder`
- Snippets: `placeholder`

**Describe the bug**
The extension on the Spicetify Marketplace is outdated.

**Screenshots**
I didnt take a screenshot, but only 4 themes are available instead of all the options shown in the description of the plugin

**Comment by ohitstom** [comment]
this is a marketplace issue, try scrolling down on the colorscheme dropdown

**Comment by ohitstom** [comment]
this is a marketplace issue, try scrolling down on the colorscheme dropdown
