### ISSUE TITLE
Add the neovim Kanagawa Color Scheme 

### ISSUE THREAD

**Issue by Hamza1K** [Comfy-Themes/Spicetify#178]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the color palette :)

**Describe alternatives you've considered**
Trying to add it myself but i am stupid and dumb

**Additional context**
Link to the color scheme Thanks in advance! :   https://github.com/rebelot/kanagawa.nvim

**Comment by ohitstom** [comment]
I have added the scheme, please feel free to open a pr with the colours modified to your liking!
