### ISSUE TITLE
[bug] settings values going below 0

### ISSUE THREAD

**Issue by dxcvvxd** [Comfy-Themes/Spicetify#182]
**Environment**
- Spotify Version: `placeholder`
- Spicetify Version: `placeholder`
- Platform (WIN, MAC, LINUX): `linucs`

**Addons**
*`[name1, name2]` or `[]` if none*
- Extensions: `placeholder`
- Custom Apps: `placeholder`
- Snippets: `placeholder`

**Spicetify Config**
*Screenshot / File Upload*
- spicetify config-dir in terminal
- config-xpui.ini

**Theme Information**
- Export Of Comfy Settings: `placeholder`
- Installed via Marketplace Or CLI: `placeholder`

**Describe the bug**
comfy settings with typeable values can go below 0 which doesnt make sense in most of the cases (i actually cant think of any case this'll be useful) so might as well fix it right 😘

**Screenshots**
![image](https://github.com/Comfy-Themes/Spicetify/assets/77129815/09751be9-a0a0-41c0-954c-82cbfe732c34)

Please also provide devtools errors/debug messages if possible:
- Spicetify enable-devtools
- open devtools (ctrl+shift+i on windows)
- enable verbose -> https://imgur.com/a/0NIAiuP
- press ctrl + r to reload

**Comment by ohitstom** [comment]
im unsure if this can be solved, this is helpful in a few options such as padding for the cover art - i've set minimum values on all the inputs already i have no idea why its ignoring them...

will do some more testing but this is put to the backburner for the moment

**Comment by ohitstom** [comment]
I've decided to only apply mins and maxes on "scroll wheel" and "up/down arrows" (e.g carousel changes) this lets the more advanced users use negative values if they want to by typing them + saves me programming headache.

important to note ive set the mins on some settings to be non existent such as custom cover art left and bottom
