### ISSUE TITLE
Incompatability with statistics app

### ISSUE THREAD

**Issue by Eatham532** [Comfy-Themes/Spicetify#183]
![image](https://github.com/Comfy-Themes/Spicetify/assets/78714349/3bee69df-6bd1-4296-9e2e-fdad7f12e8d4)

Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
Spicetify v2.32.1

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/b0cc1bf0-d80e-406b-835a-76e2e7839216)
this is an issue with the app itself
