### ISSUE TITLE
Support the new "Touchscreen UI" global nav bar.

### ISSUE THREAD

**Issue by invisiblefmx** [Comfy-Themes/Spicetify#185]
**Is your feature request related to a problem? Please describe.**

Since Spotify is rolling out the new UI as default for some people now it would be great to support it with Comfy. If thats to much work, maybe thats a thing to only do after the release of V3. The Spicetify fix for it is also just a port of their V3 solution. It also doesnt have a solution for the Sidebar config to work and it probably wont get one before v3.

**Screenshots**

![3](https://github.com/Comfy-Themes/Spicetify/assets/157469657/2170308d-16b3-425f-923e-7ffe21c849c1)
this exp. feature enables the new UI. ( Some people have it enabled by default now after Spotify updates)

![1](https://github.com/Comfy-Themes/Spicetify/assets/157469657/21b1c16b-2d66-4305-8200-1bb20c86d5ca)
new UI with Comfy theme

![2](https://github.com/Comfy-Themes/Spicetify/assets/157469657/a81021ca-f913-49e4-bf1a-6f3bbe796f79)
new UI without Comfy theme

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/78d500cd-e2c7-4e3b-be1c-b808e00fe2c8)
i dont seem to have this issue, are you certain there are no other snippets interfering? or do you have the topbar in titlebar option also enabled in comfy

**Comment by invisiblefmx** [comment]
yes it had to deactivate topbar in titlebar, but the titlebar height setting also messes with it. If you see my screenshot without theme the topbar isnt that fat. But if i lower the titlebar height in comfy settings i cant get to the result like without a theme. i can make it really low and sacrifice the window control buttons for it, or leave it this fat. But i guess people can live with that.

**Comment by ohitstom** [comment]
> yes it had to deactivate topbar in titlebar, but the titlebar height setting also messes with it. If you see my screenshot without theme the topbar isnt that fat. But if i lower the titlebar height in comfy settings i cant get to the result like without a theme. i can make it really low and sacrifice the window control buttons for it, or leave it this fat. But i guess people can live with that.

well until this new topbar is the "forced" ui as in its not an option, i cant really fix the controls because we always revert to 32px height for both the bg and the default setting for titlebar height as theres no way to get spotifys default value at any given time

i think it might be worth holding off until this is a 100% thing because spotify seems to bring this design in and out at random (over the last year its happened atleast 3 times), will keep this issue open until then though!

**Comment by ohitstom** [comment]
This is now pretty much supported, the only way that it isnt currently is if you set a custom titlebar height, then reset it - however a reload fixes this for the user.
