### ISSUE TITLE
[bug] Apple Music Gradient not moving on macOS

### ISSUE THREAD

**Issue by 10YAR** [Comfy-Themes/Spicetify#187]
**Environment**
- Spotify Version: 1.2.33.1042.g26c92729
- Spicetify Version: v2.36.2
- Platform: MAC

**Addons**
- Extensions: hidePodcasts.js, romaji-convert.js, popupLyrics.js, beautiful-lyrics.js, shuffle+.js, fullAppDisplayMod.js, listPlaylistsWithSong.js (EDIT: Also tried without any extension installed, same problem.)
- Custom Apps: none
- Snippets: none

**Spicetify Config**
Default

**Theme Information**
Pastebin: https://pastebin.com/UNibkUPu

**Describe the bug**
On Windows, my friend has an animation with the Apple Music Gradient option enabled, while I don't have that (nothing moves) with the default Apple Music Gradient options on MacOS. 

**Screenshots**
Here's a video : https://cln.sh/FNXdRgdvx8z8Z6s97Jwq

Thanks

**Comment by ohitstom** [comment]
I am unable to reproduce and fix as i do not have a mac device, are you certain this is the case on all mac devices - do you know anyone else with a mac that can test this?
