### ISSUE TITLE
[bug] Visual bug on fullscreen mode

### ISSUE THREAD

**Issue by 10YAR** [Comfy-Themes/Spicetify#188]
Environment

Spotify Version: 1.2.33.1042.g26c92729
Spicetify Version: v2.36.2
Platform: MAC
Addons:  none

Extensions: hidePodcasts.js, beautiful-lyrics.js, shuffle+.js, fullAppDisplayMod.js (EDIT: Also tried without any extension installed, same problem.)
Custom Apps: none
Snippets: none
Spicetify Config
Default

Theme Information
Pastebin: https://pastebin.com/UNibkUPu

Describe the bug
A bar appears in the fullscreen mode while listening to a song.

Screenshots
![CleanShot 2024-04-04 at 04 22 52@2x](https://github.com/Comfy-Themes/Spicetify/assets/76828073/de65d645-1d01-4ee3-a7d0-40e033ca29ea)

**Comment by ohitstom** [comment]
beautiful-lyrics is currently broken on the latest spotify so i cant actually test this until he fixes it lol
