### ISSUE TITLE
Play/Pause icon is broken

### ISSUE THREAD

**Issue by NaufalF22** [Comfy-Themes/Spicetify#19]
It doesnt happen at other theme
![image](https://user-images.githubusercontent.com/63091744/147396572-7de9a541-01ff-477c-b049-2af7d7fe80e7.png)
![image](https://user-images.githubusercontent.com/63091744/147396575-624de52b-be9e-434d-8a52-820f30e5da3e.png)

**Comment by saniok2713** [comment]
You have some theme with .js that is doing that. I have solved it by deleting all themes from Themes folder apart from Comfy and in Extensions folder all .js. then in file config-xpui.ini row extension delete and save. Maybe this will solve this problem for you :)

**Comment by ohitstom** [comment]
Closed due to inactivity.
