### ISSUE TITLE
Following You Note

### ISSUE THREAD

**Issue by TecEash1** [Comfy-Themes/Spicetify#191]
Some other themes have a following you note, I know this is an extremely niche thing which won't change much but I thought I would share the idea anyway.

Example:
<img width="99" alt="image" src="https://github.com/Comfy-Themes/Spicetify/assets/92249532/ce67ff24-bded-47db-a6a5-349f8b40d405">

**Comment by ohitstom** [comment]
whereabouts is this located in Spotify and what themes do this?

**Comment by TecEash1** [comment]
Its located in the profile menu of a user... also not sure if this is because I changed theme and then changed back but the theme may do this atm. It just blends in *alot* depending with what song your listening to (the album art).

**Comment by ohitstom** [comment]
> Its located in the profile menu of a user... also not sure if this is because I changed theme and then changed back but the theme may do this atm. It just blends in *alot* depending with what song your listening to (the album art).
> 
> Yea spotify does this normally whopps 😅

haha no worries, yeah it's a known issue some album arts cause text to blend in but I've not thought of a workaround yet, probably going to need to do some sort of colour analysis and set the text to black or white depending on circumstances
