### ISSUE TITLE
nord's playbar has a very tiny hitbox that is hard to click on

### ISSUE THREAD

**Issue by dxcvvxd** [Comfy-Themes/Spicetify#193]
**Environment**
- Spotify Version: `1:1.2.31.1205-2`
- Spicetify Version: `2.36.4`
- Platform (WIN, MAC, LINUX): `linux`

**Addons**
*`[name1, name2]` or `[]` if none*
- Extensions: `[]`
- Custom Apps: `[]`
- Snippets: `[]`

**Spicetify Config**
*Screenshot / File Upload*
- spicetify config-dir in terminal
- config-xpui.ini

**Theme Information**
- Export Of Comfy Settings: `placeholder`
- Installed via Marketplace Or CLI: `placeholder`

**Describe the bug**
nord has a very tiny playbar and thats not the issue, the issue is that it has a very tiny hitbox which you cant click on near the bottom of the spotify window because it just cuts off
i suggest making its hitbox like with no additional features but leave it unchanged visually.

**Screenshots**
![image](https://github.com/Comfy-Themes/Spicetify/assets/77129815/5d42363b-2e84-4285-b11a-96c6e11916cc)

Please also provide devtools errors/debug messages if possible:
- Spicetify enable-devtools
- open devtools (ctrl+shift+i on windows)
- enable verbose -> https://imgur.com/a/0NIAiuP
- press ctrl + r to reload

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/24551007-0a1c-4923-ba36-6443c8aaa01d)
the new clickable area
