### ISSUE TITLE
Tracklist Header rendering issue on smaller displays.

### ISSUE THREAD

**Issue by Nimai-HK** [Comfy-Themes/Spicetify#196]
Spotify for Windows (64 bit)
1.2.37.701.ge66eb7bc

Spicetify v2.36.11

Theme: Comfy / Spotify

Extensions: adblock.js, playlistIntersection.js, fullAlbumDate.js, volumePercentageWrapper.js, QueueTime.js, playlist-icons.js, npvAmbience.js, scannables.js, quickQueue.js, utilities.js, cacheCleaner.js, hidePodcasts.js, CoverAmbience.js

Custom apps: marketplace

xpui_2024-05-03_1714757530304_e66eb7b
cef_122.1.13+gde5b724+chromium-122.0.6261.130

Runtime: Chrome

Build System: CMake

- Platform (WIN)

*Applicable to Manual and Marketplace Installation*

**Describe the bug**
![image](https://github.com/Comfy-Themes/Spicetify/assets/169251488/64e2f129-75d1-44fe-ab80-6701e1993b05)
Top of any opened album or artist page is hidden/missing due to the layout. Seems to merge into Titlebar.

Spicetify automatic installation (powershell)
Spotify downloaded from Website.

devtools enabled.

**Comment by ohitstom** [comment]
are you certain this doesn't happen without the theme?

**Comment by Nimai-HK** [comment]
it doesn't happen without the theme.
Btw went through again, after an update it stopped happening with the artist pages.
Only playlists are affected

**Comment by Nimai-HK** [comment]
bro by the way, serious respect. The time in which u responded, very quick, Never seen such an involved dev, Respect

**Comment by ohitstom** [comment]
> Only playlists are affected

I'll see what I can do but this is quite an extreme edge case to have a monitor this small, if I can recreate it I can probably fix it
