### ISSUE TITLE
Windows 11 look alike colours.ini file modified

### ISSUE THREAD

**Issue by Nimai-HK** [Comfy-Themes/Spicetify#197]
![image](https://github.com/Comfy-Themes/Spicetify/assets/169251488/aabd24c1-8c3b-4d92-b65b-b43c219ecec7)

Is there a chance this can be added?

Result:
![image](https://github.com/Comfy-Themes/Spicetify/assets/169251488/de11b634-8b04-46e6-991b-83cee295ff3f)

**Comment by ohitstom** [comment]
correct me if I'm wrong but is this not near identical to the mono colorscheme?

**Comment by Nimai-HK** [comment]
it is almost identical, but the colours in the mono scheme are darker, with accent colour being white, while this is blue. 
just minor modification.
 I can't code, my original intent was to make the sidebar also dark like the playing now bar, to give the " Microsoft " feel. I couldn't find a way to do that, forgot to mention this.
refer Microsoft store, and that colour was my attempt

**Comment by ohitstom** [comment]
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/0afc47d0-1cbf-4208-99be-9a58b0d9ca71)
im not sure on adding this since the lunar scheme already exists and is pretty much identical

**Comment by Nimai-HK** [comment]
It's fine
just an idea. No need to add this
seems to be that mines just a combination of lunar and mono..
