### ISSUE TITLE
Playlists panel can't show all playlists

### ISSUE THREAD

**Issue by ASTRELION** [Comfy-Themes/Spicetify#20]
The left panel where playlists are shown seems to not be able to handle a great number of playlists. I have 38 items visible (including 1 folder and 37 playlists) but in reality I have more like 6 folders and many more playlists.

Able to view all folders when 'Playlists' folder is collapsed:
![image](https://user-images.githubusercontent.com/20118782/148041464-b23efa80-6825-4b1f-b01f-6762f6750ff5.png)

Cannot see all playlists in 'Playlists' folder and the rest of my folders are also not visible:
![image](https://user-images.githubusercontent.com/20118782/148041567-73cd41f4-4af9-41af-8d18-295c8efed9eb.png)

**Comment by ianrispin** [comment]
I have the same issue

**Comment by Zekkun23** [comment]
I dont have the same issue, but whenever I get down to the bottom of my playlists, the scroll bar suddenly goes up so I cant access the rest of my playlists.

**Comment by ianrispin** [comment]
I actually managed to fix that by messing around with the code a bit, but I couldn't figure out how to fix the playlist clipping.

**Comment by RyanTheTechMan** [comment]
> I dont have the same issue, but whenever I get down to the bottom of my playlists, the scroll bar suddenly goes up so I cant access the rest of my playlists.

I have this same issue. How did you fix it @ianrispin?

**Comment by ianrispin** [comment]
I had to mess around with the css file, I can share my changes here if you want.

**Comment by NYRI4** [comment]
I finally pushed a fix, should be good now

**Comment by RyanTheTechMan** [comment]
Thanks! You fixed my issue :)
