### ISSUE TITLE
Apple music Gradient causes screen to tear

### ISSUE THREAD

**Issue by Magniquick** [Comfy-Themes/Spicetify#200]
from the discord: https://discord.com/channels/842219447716151306/842818946243887134/1246188906542661763
Relavant info to reproduce: [whoneedsnix.txt](https://github.com/user-attachments/files/15522000/whoneedsnix.txt)

**Comment by ohitstom** [comment]
could you check if this selector evaluates in inspect element:
`:root .Root__main-view .main-view-container main:not(:has(.lyrics-lyricsContainer-LyricsContainer))`

**Comment by Mysticc28** [comment]
Same issue, affects playlists and fullscreen menu. Have tried reinstalling both spotify and spicetify with and without other extensions, does not work now. 
![image_2024-10-27_111151487](https://github.com/user-attachments/assets/e1e599ee-d05c-4b8f-91f4-e1b4129f2242)
![image](https://github.com/user-attachments/assets/7f3de7cc-dbc0-474b-8ca8-836cdd8fddd1)
