### ISSUE TITLE
Move filter bar in Home

### ISSUE THREAD

**Issue by kernelb00t** [Comfy-Themes/Spicetify#202]
**Is your feature request related to a problem? Please describe.**
When on little screens, every pixel is important. The default design is not very efficient. This bar, containing "All", "Music" and "Podcasts", is here for nothing. 
![image](https://github.com/Comfy-Themes/Spicetify/assets/68474172/b8a913ab-ecf6-4b57-81b5-5350ed913fc7)

**Describe the solution you'd like**
It could be moved next to the navigation buttons.

**Describe alternatives you've considered**
I don't have the time to check it myself and submit the change. I would think that it needs some JS to move the HTML inside of this bar.

**Comment by ohitstom** [comment]
I'm not really committed to changing Spotifys layout this drastically, if it's achievable in just CSS then I will consider it.

I probably won't get to this issue for a while so if you look into it in the meantime and have any relevent CSS feel free to post it here

**Comment by ohitstom** [comment]
please create a snippet for this
