### ISSUE TITLE
Custom font not work

### ISSUE THREAD

**Issue by natholdallas** [Comfy-Themes/Spicetify#205]
![image](https://github.com/user-attachments/assets/f1773415-76d2-42f3-8130-5733d540095d)
in this window can work but in this window....
![image](https://github.com/user-attachments/assets/67ad00d1-f532-412b-8441-4af2de09bca7)

**Comment by natholdallas** [comment]
i use linux, I not sure this bug about windows

**Comment by ohitstom** [comment]
what spotify version are you on

**Comment by natholdallas** [comment]
![image](https://github.com/user-attachments/assets/3da7194d-1a69-4785-8514-3aac6e4f9021)

**Comment by ohitstom** [comment]
could you send your comfy config (the export at the bottom of our settings menu) and anything else you have installed to do with spotify / spicetify

**Comment by natholdallas** [comment]
![image](https://github.com/user-attachments/assets/93ec2b0b-fc1c-4085-8964-c4113ad3ecef)

**Comment by natholdallas** [comment]
this folder i couldn't found any about comfy's config.... i don't know where is the config folder

**Comment by ohitstom** [comment]
So the issue is linux has an outdated spotify version, i cant support custom fonts on both 1.2.42 and >1.2.42 because spotify completely changed how their fonts work - please either downgrade the theme installed locally or wait for a spotify update!

**Comment by ohitstom** [comment]
one second im going to try one thing that might remedy this, please try the latest commit and if you are using marketplace make sure your cache is cleared (this could take a full spotify restart or you can inspect element and refresh with the cache setting off in the network tab)

if this doesnt work im afraid there isnt much i can do :/

**Comment by ohitstom** [comment]
will close due to inactivity soon

**Comment by natholdallas** [comment]
in currently version, it's works good,i can use custom font in spotify,thx
