### ISSUE TITLE
Device picker menu issue on spicetify

### ISSUE THREAD

**Issue by Boddycr** [Comfy-Themes/Spicetify#206]
![image](https://github.com/user-attachments/assets/74be2d7e-5d5d-4767-9f75-d7088cb408ea)

Version 
![image](https://github.com/user-attachments/assets/9318237c-7dac-450b-8bb5-fab50786ea46)

**Comment by ohitstom** [comment]
![image](https://github.com/user-attachments/assets/d68bfe2d-53b5-4b8a-9960-492ed6ece97b)
hi sorry i cant seem to replicate this issue, is it still present and/or is there anything else that could be causing this you can think of?
