### ISSUE TITLE
the background is clipping with the top of the search bar.

### ISSUE THREAD

**Issue by mintorsmthidk** [Comfy-Themes/Spicetify#210]
to be straightfoward, with the latest spotify ui update (search bar pushed to the top), the background's been clipping with the search bar on the top of the screen

**Comment by ohitstom** [comment]
could you provide pictures and info on your versions?

**Comment by Thecrunchyderp** [comment]
I know I'm not OP but I'm experiencing it as well

Spotify 1.2.47
Spicetify 2.38.3

![Screenshot 2024-09-26 170121](https://github.com/user-attachments/assets/bcedf0b8-fd88-4e7d-b2ab-269c31c6c801)

**Comment by ohitstom** [comment]
> I know I'm not OP but I'm experiencing it as well
> 
> Spotify 1.2.47
> Spicetify 2.38.3
> 
> ![Screenshot 2024-09-26 170121](https://github.com/user-attachments/assets/bcedf0b8-fd88-4e7d-b2ab-269c31c6c801)
> 

you have set your titlebar height way too low, please run spicetify enable-devtools, open inspect element and run Comfy.Reset() in the console tab

**Comment by Thecrunchyderp** [comment]
I just got blasted with errors after running Comfy.Reset()

![Screenshot 2024-09-26 172149](https://github.com/user-attachments/assets/833af676-265c-4009-a936-d10f7d4e5621)
