### ISSUE TITLE
Tracklist Layout Broken

### ISSUE THREAD

**Issue by platz-halter** [Comfy-Themes/Spicetify#211]
**Environment**
- Spotify Version: 1.2.47.364.gf06e5cee
- Spicetify Version: Dev (AUR: spicetify-cli-git latest release)
- Platform (WIN, MAC, LINUX): Arch Linux

**Addons**
- None

**Spicetify Config**
- spicetify config-dir in terminal: ~/.config/spicetify
- config-xpui.ini: [config-xpui.ini.txt](https://github.com/user-attachments/files/17174954/config-xpui.ini.txt)

**Theme Information**
- Export Of Comfy Settings: [export_of_settings.txt](https://github.com/user-attachments/files/17174944/export_of_settings.txt)
- Default settings
- Installed via Marketplace Or CLI: marketplace

**Describe the bug**
Text look weird and cramped together.
Changing zoom changes nothing.
Trying to change the font also had almost no improvement.

**Screenshots**
![2024-09-28-172511_hyprshot](https://github.com/user-attachments/assets/671ebc60-2139-4675-99ec-c00c866ce875)

Please also provide devtools errors/debug messages if possible:
- Not possible

**Comment by sanoojes** [comment]
may be it is due to your patch try removing those

```
xpui.js_find_0880 = COLLAPSED\?64:32
xpui.js_repl_0880 = COLLAPSED?32:32
xpui.js_find_8008 = ,(\w+=)56,
xpui.js_repl_8008 = ,${1}32,

```

**Comment by ohitstom** [comment]
Could you make sure you have nothing else installed messing with this, our theme shouldn't be doing this...

**Comment by ohitstom** [comment]
> may be it is due to your patch try removing those
> 
> ```
> xpui.js_find_0880 = COLLAPSED\?64:32
> xpui.js_repl_0880 = COLLAPSED?32:32
> xpui.js_find_8008 = ,(\w+=)56,
> xpui.js_repl_8008 = ,${1}32,
> 
> ```
 
exactly right

**Comment by platz-halter** [comment]
Thank you for the quick help.
Removing the patches and reapplying resolved the issue
