### ISSUE TITLE
Issue where top 3 songs of an album or playlist doesnt connect with the background

### ISSUE THREAD

**Issue by dainosor** [Comfy-Themes/Spicetify#214]
![{80AF8F30-8BC6-403E-A0B6-AB93553F0A74}](https://github.com/user-attachments/assets/9cb08d0c-e971-496f-ba6a-82e03fc72cd8)

**Comment by ohitstom** [comment]
waiting on a spicetify update to fix this I will keep you posted

**Comment by ohitstom** [comment]
reapply Spotify should work now

**Comment by dainosor** [comment]
its still the same

**Comment by ohitstom** [comment]
> its still the same 

did you run spicetify restore backup apply again

**Comment by dainosor** [comment]
i did anything else but that, thanks it works now
