### ISSUE TITLE
Playlists banners shifted into lists, while the main banner is the default colour

### ISSUE THREAD

**Issue by Nimai-HK** [Comfy-Themes/Spicetify#215]
Spotify for Windows (64 bit)
1.2.49.439.gfae492c7
Spicetify v2.38.4
Theme: Comfy / Mono
Extensions: adblock.js, QueueTime.js, quickQueue.js, showQueueDuration.js, npvAmbience.js, scannables.js, playlist-icons.js, fullAlbumDate.js, find-duplicates.js, oldLikeButton.js, cacheCleaner.js, keyboardShortcut.js, volumePercentageWrapper.js
Custom apps: marketplace, lyrixed

<img width="594" alt="image" src="https://github.com/user-attachments/assets/c9537138-2a92-4956-89b9-e20d967b6488">

Sleepy as heck, ik what i said sounds like im drunk, just check the image

**Comment by ohitstom** [comment]
run spicetify restore backup apply
