### ISSUE TITLE
my playlist images are squashed

### ISSUE THREAD

**Issue by esvuv** [Comfy-Themes/Spicetify#25]
![image](https://user-images.githubusercontent.com/90131796/153217403-3465b68c-7ec9-4382-8afe-a3e62af90e17.png)

my images from playlist are wide af.. how to fix that?

**Comment by klumey** [comment]
I just downloaded this theme and I have the same issue :/

**Comment by klumey** [comment]
Okay, I probably found a solution (sorry if it doesn't work). So, I tried different theme, and this was still there, so I deleted all extensions and turned my spotify to deafult. After that tried using the theme and it worked.
But it isn't exactly with Comfy theme, so the issue could be the comfy extension having a trouble with new update.

**Comment by ohitstom** [comment]
Spicetify Related Issue.
