### ISSUE TITLE
Makes Spotify Blank

### ISSUE THREAD

**Issue by dlyynn** [Comfy-Themes/Spicetify#27]
Recently it started simply making the entire Spotify blank, not sure if this is a spicetify issue or an issue with the theme in general
![Screenshot 2022-02-25 233311](https://user-images.githubusercontent.com/100419289/155715974-d91f070c-fd37-4071-8bf9-37d8f038ffff.png)
.

**Comment by NYRI4** [comment]
It is surely an issue on Spicetify's end, not mine

**Comment by ohitstom** [comment]
https://github.com/spicetify/spicetify-cli/issues/1483 @NYRI4

**Comment by Ushie** [comment]
> [spicetify/spicetify-cli#1483](https://github.com/spicetify/spicetify-cli/issues/1483) @NYRI4

that doesn't look like the same issue this person is having (this one is fully blank instead of partially), Nyria has already removed that part of the code 6 days ago

**Comment by Toflamo** [comment]
I have the same problem! And it's not only with this theme, any theme that I install comes with the same blank screen

**Comment by incogg** [comment]
It's a Spicetify issue, just reinstall Spotify.

**Comment by Chr1s70ph** [comment]
I had the exact same issue.

> It's a Spicetify issue, just reinstall Spotify.

This fixed it for me 👆🏽
```bash
$ spicetify restore
(update sptotify and spicetify with your package manager or however you install your programs)
$ spicetify --version 
(make sure you are using version 2.9.2)
$ spotify --version
(make sure you are using at least version 1.1.80)
$ spicetify restore backup apply
```
> Not sure about the spotify version number exactly, correct me if I'm wrong

**Comment by ohitstom** [comment]
Another Spicetify related issue.
