### ISSUE TITLE
Now_Playing_Bar

### ISSUE THREAD

**Issue by deathjHK** [Comfy-Themes/Spicetify#28]
So I suddenly stumbled over Spicetify recently and instantly got hooked on the Comfy theme.
The only issue I have with this theme is the NowPlayingBar - since i try to match all the colors to the ones of my setup.

As I looked into the sheets i discovered the color code for the bar several times and changed the ones in local files to my desired color - but this is where the problem starts.
Due to update reasons the user.css is an import of the current app.css from github. If i try to get a local one pulled or one from the web, where only the color code for the bar is changed, the NowPlayingBar goes back to being normal and small just like the original one (but the colors is changed).

So now my question is: 
Is there any way I can have the NowPlayingBar from the Comfy theme but in my desired colors?

**Comment by ohitstom** [comment]
yes there is you just have to try harder

**Comment by ohitstom** [comment]
Irrelevant to the repo and its causes, if you still want this support ask on the spicetify discord server, lots of us devs are around there.
