### ISSUE TITLE
Play button overlaps track title in album list view

### ISSUE THREAD

**Issue by kyrie25** [Comfy-Themes/Spicetify#30]
I've noticed that the play button would overlap on track title in album list view, which makes elements underneath (artists' names) sometimes unclickable.
I'm guessing it has to do with somewhere around this part:
https://github.com/Comfy-Themes/Spicetify/blob/6935099bc74611e633be17a1e555a84b19cc094e/assets/_main.scss#L83
But I'm hopeless with CSS so I can't provide a patch of my own, really appreciate if you'd take the time looking into my issue.

![Spotify_DCkSddZzEW](https://user-images.githubusercontent.com/77577746/166940105-f132605a-a47e-45c0-bf78-17a8ac6c89e5.gif)

Great theme btw, keep up the good work!

**Comment by ohitstom** [comment]
I have had similar issues on my branch of comfy and did manage to fix it, i'll look into getting those changes merged into main once this repos been refactored

**Comment by xVANKO** [comment]
.main-trackList-rowSectionStart{margin-left:40px}

**Comment by ohitstom** [comment]
Upcoming fix

**Comment by lhvy** [comment]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/40507205/181863487-6b3b96b5-f948-4c8f-89d8-acef44ef9f39.png">

If this is the issue you're describing, it's still happening on the latest release of Comfy, Spicetify, and latest supported Spotify release. Is the fix coming soon?

**Comment by kyrie25** [comment]
Resolved via bff44278d32de649eb32c4f1967bc3733651ccab
