### ISSUE TITLE
Playlist scroll bar won't scroll all the way

### ISSUE THREAD

**Issue by lhvy** [Comfy-Themes/Spicetify#33]
I create/follow a large number of playlists, and I've just noticed that I can't scroll all the way down.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/40507205/169691621-bc33c2f4-85eb-4bca-a6b7-6561ff89ce11.png">

<img width="320" alt="image" src="https://user-images.githubusercontent.com/40507205/169691630-b8fc6ccd-341e-4c38-bf98-b3f52a802f85.png">

In both of these screenshots, neither of the scroll bars will go down any further. Interestingly after expanding and shrinking the album art, the playlists are now offset by one:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/40507205/169691666-52924fc1-a1b6-4c5c-99f4-b89cbdb64ba7.png">

This is with Spotify 1.1.84, Spicetify 2.9.8 and the latest version of Comfy installed using the macOS install script maybe 30 minutes ago.

**Comment by lhvy** [comment]
Not sure if this is related, but my sidebar doesn't match the screenshots in the readme either?

<img width="301" alt="image" src="https://user-images.githubusercontent.com/40507205/169692281-722eabc5-2c3f-49c7-b138-5fa47dcb85a1.png">

(The create playlist and liked songs icons aren't the same and also the centred text that says "Playlists" is missing. Also I think the slightly dimmed background around the playlists isn't there too.)

**Comment by ohitstom** [comment]
I will test this out in a bit and let you know!

**Comment by ohitstom** [comment]
1.1.84 is extremely broken at the moment, I suggest downgrading to 1.1.83 for the moment.

Once spicetify is updated and supports 1.1.85, I will update the theme to support said versions.

It's pointless for me to update the theme only for classes to be changed and I'd have to redo it all!

**Comment by lhvy** [comment]
Speak of the devil, 1.1.85 support was *just* added in Spicetify 2.8.9

**Comment by ohitstom** [comment]
Doesnt seem to patch 85 just yet, was more of a bugfix update it seems
