### ISSUE TITLE
Move multiple themes to a single one

### ISSUE THREAD

**Issue by afonsojramos** [Comfy-Themes/Spicetify#37]
Why are three separate themes created? Can't it be moved to just one?

I am raising this issue because for Spicetify Marketplace we may move towards requiring theme creators to have one repo per theme, although, exceptions may apply.

**Comment by afonsojramos** [comment]
This is just for measuring popularity... But I may opt for a different solution...

**Comment by lhvy** [comment]
> I'm not personally willing to work around marketplace as each theme has some distinct differences

If the themes have distinctly different JS and CSS, should they just have different names and repos, instead of calling them all Comfy-X, giving the impression that they're simple colour variants of one theme?

**Comment by ohitstom** [comment]
No
