### ISSUE TITLE
Time stamp overlapping

### ISSUE THREAD

**Issue by nobucula** [Comfy-Themes/Spicetify#46]
Song duration timer is visually quite unpleasand right below the artist display in the bottom left corner
![Bildschirmfoto 2022-05-30 um 16 33 56](https://user-images.githubusercontent.com/21077995/171014400-7ebd4478-e710-4b04-8b30-2acdf78e24f3.png)

**Comment by ohitstom** [comment]
May i suggest using the versions that comfy supports up to, reference the main readme.

Unfortunately it is exam season so no one has time to work on a whole lot at the moment.
