### ISSUE TITLE
Current time during song overlaps the Artist Name

### ISSUE THREAD

**Issue by bebguin** [Comfy-Themes/Spicetify#54]
![image](https://user-images.githubusercontent.com/82475058/172246590-3fbc9a42-fb5f-4a03-8632-eb7a978dbd71.png)

I installed the theme and this happened? Any idea how to fix?

**Comment by kyrie25** [comment]
Duplicate of #46.

**Comment by bebguin** [comment]
> Duplicate of #46.

Do you know how I can get an older version of Spotify? All of the download links seem to just install 1.1.86.
