### ISSUE TITLE
Theme doesn't apply properly when launching Spotify

### ISSUE THREAD

**Issue by sph3** [Comfy-Themes/Spicetify#60]
Spicetify version: 2.9.9 (edit: happens in 2.10.2 too)
Spotify version: 1.1.84.716.gc5f8b819

When launching Spotify normally, only the colors are applied but all the other styles are not. Like the top bar, sidebar paddings, card style and album/playlist view with the current song cover as background. Nothing is loaded.

However, when Spotify is restarted through `spicetify apply`, everything works fine. When I close and reopen it manually though, the theme isn't applied again.

**Comment by kyrie25** [comment]
Sounds like a Spicetify issue. Does it occur while using other themes?

**Comment by ohitstom** [comment]
You are using a version of spotify and spicetify that do not support this theme. Downgrade to 2.9.8 and 1.1.83,
OR use 2.10.2 and LATEST spotify.
