### ISSUE TITLE
Playlist doesn't take input from mouse but recognize keyboard input.

### ISSUE THREAD

**Issue by Vathanak7** [Comfy-Themes/Spicetify#62]
[Mouse](https://i.imgur.com/mNn2THF.png) 

[Keyboard](https://i.imgur.com/OMq4j8M.png)

Spotify for Windows
1.1.88.612.gcc529952

Spicetify lastest version

**Comment by kyrie25** [comment]
Patched via 6da535b29252aab586e48192ee2af5a583d81c41
