### ISSUE TITLE
Profile and play button acting buggy

### ISSUE THREAD

**Issue by Paxxous** [Comfy-Themes/Spicetify#63]
I installed Comfy through the automatic installation, and found that the ui is acting a bit funky:

![profile](https://user-images.githubusercontent.com/88162094/177039777-1aa97761-c88c-4e85-9206-fc4b1a75f027.png)
![play](https://user-images.githubusercontent.com/88162094/177039778-f9c41334-254c-4198-a76f-bf679d5dd735.png)

It seems like the sprite-sheet for the play-button is off and the profile is stretched

I'm using Spotify for Windows 1.1.88.612.gcc529952 alongside Spicetify 2.10.2 (the newest version as of current)

**Comment by kyrie25** [comment]
Do you have any other themes/extension installed (eg. via Marketplace) that could be conflicting with Comfy?
Because that is *not* how Comfy controls are supposed to look like and doesn't exist anywhere in the stylesheet

![image](https://user-images.githubusercontent.com/77577746/177042912-cfe5dde3-64e3-4acc-91d1-b2e0eb5d8019.png)

**Comment by Paxxous** [comment]
> Do you have any other themes/extension installed (eg. via Marketplace) that could be conflicting with Comfy? Because that is _not_ how Comfy controls are supposed to look like and doesn't exist anywhere in the stylesheet
> 
> ![image](https://user-images.githubusercontent.com/77577746/177042912-cfe5dde3-64e3-4acc-91d1-b2e0eb5d8019.png)

Reinstalling Spicetify did the trick, though the issue with the stretched profile is recurring.

**Comment by ohitstom** [comment]
The issue with the stretched profile happens with a lot of themes, you will need to set a pfp to fix this.

**Comment by Paxxous** [comment]
> 

alright
