### ISSUE TITLE
button-hover in color.ini

### ISSUE THREAD

**Issue by Lethaquell** [Comfy-Themes/Spicetify#66]
Could you please add button-hover option to color.ini?

**Comment by kyrie25** [comment]
- `button-active` **is** the hover color for buttons

- `button-hover` is not a valid key for Spicetify:
![image](https://user-images.githubusercontent.com/77577746/180985769-b234314f-04ec-4202-b53f-9c948bd4005d.png)

**Comment by kyrie25** [comment]
I have no idea where you got that key from, or what theme gave you the idea but `button-hover` has never been a thing and we will not add it.
