### ISSUE TITLE
Paus/play-button is looking weird

### ISSUE THREAD

**Issue by Sefohui** [Comfy-Themes/Spicetify#71]
Hi! Love the theme! But unfortunally it seems like the play/paus button is multiplying itself. Is there a soulution to fix that?

**Comment by Sefohui** [comment]
Forgot to add the screens :/ 
![image](https://user-images.githubusercontent.com/69700015/184500790-d7d44b54-c421-482f-8acf-86f2795b2877.png)
![image](https://user-images.githubusercontent.com/69700015/184500798-95559ea4-a57d-45a0-ae56-54605970beb2.png)

**Comment by kyrie25** [comment]
Send screenshot + config.

**Comment by Sefohui** [comment]
Aa the config. Ofc. I'm guessing config-xpui
`[Setting]
prefs_path              = C:\Users\kevin\AppData\Roaming\Spotify\prefs
color_scheme            = Comfy
inject_css              = 1
overwrite_assets        = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\kevin\AppData\Roaming\Spotify
current_theme           = Comfy
replace_colors          = 1
spotify_launch_flags    = 

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

[AdditionalOptions]
extensions            = bloom.js|comfy.js
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

; DO NOT CHANGE!
[Backup]
version = 1.1.88.612.gcc529952
with    = 2.10.2

`

**Comment by kyrie25** [comment]
Bloom extension conflict issue, remove the extension. I had a hunch when the Play button looked like Bloom's as this is what Comfy's look like.
![image](https://user-images.githubusercontent.com/77577746/184500941-9df75179-f517-4a1b-a07d-9e1f6a4fc280.png)

**Comment by Sefohui** [comment]
Aa. Makes sense. Awesome! Thank you! :D
