### ISSUE TITLE
Custom Apps disappears

### ISSUE THREAD

**Issue by CoolJosh0221** [Comfy-Themes/Spicetify#72]
When I use this extension, my custom apps went disappeared
With Comfy
<img width="260" alt="Screen Shot 2022-08-27 at 3 04 37 PM" src="https://user-images.githubusercontent.com/88709160/187019218-03290e25-bb04-40bc-bbaf-a6e0ddf97c2a.png">

Without Comfy

<img width="199" alt="Screen Shot 2022-08-27 at 3 04 53 PM" src="https://user-images.githubusercontent.com/88709160/187019245-f276920f-5ec2-4b1d-b80a-c5a24fc6ed15.png">

**Comment by ohitstom** [comment]
I noticed this today. I assume its something @kyrie25 did in recent commits and didnt test properly in dev branch tsk tsk....

Will look into it at some point, feel free to go back a few commits whilst you wait.

**Comment by kyrie25** [comment]
> I noticed this today. I assume its something @kyrie25 did in recent commits and didnt test properly in dev branch tsk tsk....
> 
> 
> 
> Will look into it at some point, feel free to go back a few commits whilst you wait.

Bruh this has been a thing before I came along. Remember you trying to install Marketplace with the capital M in folder name and it disappeared also 💀

**Comment by kyrie25** [comment]
Custom Apps are hard-coded, so are their positions, no idea why Nyria did this.

**Comment by ohitstom** [comment]
I mean it's definitely due to one of your commits lol, I've never had an issue using marketplace and lyrics plus at the same time, now there's a massive gap and pseudo customapp there

**Comment by CoolJosh0221** [comment]
So would the problem be fixed?

**Comment by ohitstom** [comment]
> > So would the problem be fixed?
> 
> Fixed in our Development branch, will be published soon enough.

I'll do more stuff on dev tonight, I have some stuff done already I need to push

**Comment by ohitstom** [comment]
Merging tonight, will close this now.
