### ISSUE TITLE
Option to show the numbers back?

### ISSUE THREAD

**Issue by karimawii** [Comfy-Themes/Spicetify#73]
Hey, I know some people don't like the numbers in the playlists, but I kinda need them to remember how further I went in a playlist, cause, you know Spotify doesn't have bookmarks or smth 🙃, so pls tell me how I can edit the css to show them or maybe add an option to show/hide them.

![image](https://user-images.githubusercontent.com/69881381/187440605-9f92896e-fbf7-471e-8676-2af5f88abc4a.png)

**Comment by ohitstom** [comment]
Adding an option wouldnt really be viable, hop on over to the spicetify discord server, open a ticket, and ping @tominator and @kyrie, and we can help you out.

To add a toggle-able option we'd have to write our own buggy css hotloading etc like dribbblish.
