### ISSUE TITLE
Custom app icons are missing

### ISSUE THREAD

**Issue by theRealPadster** [Comfy-Themes/Spicetify#75]
It would be nice to fall back to the custom app's built-in icon if there's not a custom Comfy one. 
<img width="270" alt="image" src="https://user-images.githubusercontent.com/1565883/187567495-86df2a80-2de7-45df-a826-3a2f9ede9486.png">

**Comment by ohitstom** [comment]
Will look into adding this

**Comment by kyrie25** [comment]
Resolved via fbbc5fb27fdf0a42bf09a1d7e7cec26fe752e26b
