### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by WoodendotZz** [Comfy-Themes/Spicetify#82]
The display area of the timeline conflicts with other components.
![image](https://user-images.githubusercontent.com/95269885/192951996-91389588-9010-4871-b2fc-b91029f4856c.png)
![image](https://user-images.githubusercontent.com/95269885/192952036-5ee7e9e3-d708-4349-a06a-79f04daa77c0.png)
It looks strange.

**Comment by ohitstom** [comment]
Downgrade to the supported versions.
