### ISSUE TITLE
Add the ability to choose a static banner image for `#mainImage` in comfy settings

### ISSUE THREAD

**Issue by ohitstom** [Comfy-Themes/Spicetify#89]
Add a snippet to comfy settings menu that allows for the input of a static banner via url

**Comment by ohitstom** [comment]
```js
async function loadImage() {
    const [fh] = await window.showOpenFilePicker();
    var file2 = await fh.getFile();
    var name = file2.name;
    var fr = new FileReader();
    fr.readAsDataURL(file2);
    return new Promise((resolve, reject) => {
      fr.onloadend = function() {
        resolve(fr.result);
      }
    });
}

url = await loadImage();
const banner = document.querySelector("#mainImage")
banner.style = ("background-image: url('" + url.replace(/(\r\n|\n|\r)/gm, "") + "')")
```

For future reference. Simply adding the base64 to localstorage and adding some logic should suffice.

**Comment by zEROma25** [comment]
> Add a snippet to comfy settings menu that allows for the input of a static banner via url

When activated without URL, a white glow appears in the upper left corner. Is this how it should be?
![image](https://github.com/Comfy-Themes/Spicetify/assets/58146362/79d31cd3-69f0-40bd-9f64-4e2eee202f34)

**Comment by zEROma25** [comment]
> you can technically just find a transparent image on Google and use that?

I didn't think about it, so I'll do it.

> idk if writing the extra logic is worth it

It's not worth wasting your time.

**Comment by ohitstom** [comment]
> > you can technically just find a transparent image on Google and use that?
> 
> I didn't think about it, so I'll do it.
> 
> > idk if writing the extra logic is worth it
> 
> It's not worth wasting your time.

not a waste at all more just it would require a lot of juggling of the logic, if the transparent image doesn't work I'm happy to fix it though if it does that's just a quicker fix to your issue is all

**Comment by zEROma25** [comment]
> not a waste at all more just it would require a lot of juggling of the logic, if the transparent image doesn't work I'm happy to fix it though if it does that's just a quicker fix to your issue is all

It works. Thank you!
