### ISSUE TITLE
Snippet Issue: Right Side Cover Art

### ISSUE THREAD

**Issue by Nova1ite** [Comfy-Themes/Spicetify#95]
![Untitled3](https://user-images.githubusercontent.com/115776661/195785647-4e38308e-9e3e-47a5-96e8-4947aa546a6c.png)

**Comment by Nova1ite** [comment]
Seems like you're working on the expanded flyout to the right side for the album art, similar to this snippet....
Nevermind then

**Comment by ohitstom** [comment]
#92
