### ISSUE TITLE
Album art no longer hovering above

### ISSUE THREAD

**Issue by ququiq** [Comfy-Themes/Spicetify#96]
It happened quite recently? Strange as I don't have spotify up to date yet this happened.

**Comment by ququiq** [comment]
> 

![Screenshot 2022-10-18 003835](https://user-images.githubusercontent.com/101261337/196235872-01902cec-fc28-42a7-8806-6773fcaf8436.png)
yes the music was playing

**Comment by ohitstom** [comment]
![image](https://user-images.githubusercontent.com/22730962/196240473-bacd2ea8-1114-4591-9f3c-f198e1ef0724.png)
its fine for me
