### ISSUE TITLE
how do i remove the backround image pls help its not like that before and its realy ugly on my opinion

### ISSUE THREAD

**Issue by Ekel1738** [Comfy-Themes/Spicetify#98]
![Screenshot (220)](https://user-images.githubusercontent.com/116428296/197328871-1e794031-083d-4169-acf4-b8e8e5a1010c.png)

**Comment by framie** [comment]
Add this CSS snippet to remove the background cover art
```
#mainImage {
    background-image: none !important;
}
```

**Comment by ohitstom** [comment]
Don't create issues on personal preference.
It's a one way ticket to being ignored.
